In [1]:
import pandas as pd

In [2]:
import pickle
with open('summary.pickle', 'rb') as f:
    summary = pickle.load(f)

In [3]:
#count값 작은것 부터 나열
sort_summary =summary.sort_values(by=['count'], axis=0)
sort_summary.reset_index(drop=True)

         id                                            current count Label
0     82561  [0.0027656555175781, 0.0027167797088623, 0.002...     1  None
1     82261  [0.0033807754516601, 0.00335693359375, 0.00336...     1  None
2     83191  [0.0070524215698242, 0.0070703029632568, 0.007...     1  None
3     83192  [0.0050771236419677, 0.005044937133789, 0.0050...     2  None
4     81976  [0.0057041645050048, 0.0057029724121093, 0.005...     2  None
...     ...                                                ...   ...   ...
1176  83186  [0.0039851665496826, 0.0039350986480712, 0.003...   326  True
1177  83187  [0.0036191940307617, 0.003587007522583, 0.0035...   327  True
1178  83188  [0.0062942504882812, 0.0062811374664306, 0.006...   328  True
1179  83189  [0.0033390522003173, 0.0033378601074218, 0.003...   329  True
1180  83190  [0.0047111511230468, 0.0046968460083007, 0.004...   330  True

[1181 rows x 4 columns]

In [4]:
#false true 슬라이싱
falseData = sort_summary[10:60]
trueData = sort_summary[1131:]

#labeling
falseData['Label'] = False
trueData['Label']=True

#concat
trainData = pd.concat([falseData,trueData])

<ipython-input-4-a5ac41bff520>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  falseData['Label'] = False
<ipython-input-4-a5ac41bff520>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trueData['Label']=True

In [5]:
trainData

         id                                            current count  Label
306   81977  [0.0368130207061768, 0.0367355346679688, 0.036...     3  False
134   82564  [0.0028514862060546, 0.0028395652770996, 0.002...     4  False
4     81978  [0.0223100185394287, 0.0222086906433105, 0.022...     4  False
313   82264  [0.0302565097808838, 0.0301182270050049, 0.029...     4  False
753   83194  [0.0034606456756591, 0.0034451484680175, 0.003...     4  False
...     ...                                                ...   ...    ...
575   83186  [0.0039851665496826, 0.0039350986480712, 0.003...   326   True
1071  83187  [0.0036191940307617, 0.003587007522583, 0.0035...   327   True
569   83188  [0.0062942504882812, 0.0062811374664306, 0.006...   328   True
751   83189  [0.0033390522003173, 0.0033378601074218, 0.003...   329   True
767   83190  [0.0047111511230468, 0.0046968460083007, 0.004...   330   True

[100 rows x 4 columns]

In [6]:
pickle.dump(trainData, open("trainData.pickle", "wb" ))